# Generated by Django 4.1 on 2022-09-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile_store", "0002_user_is_verified_user_otp"),
    ]

    operations = [
        migrations.CreateModel(
            name="MobilePhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=256)),
                ("camera_spec", models.CharField(max_length=64)),
                (
                    "model_ram",
                    models.CharField(
                        choices=[
                            ("2", "2GB"),
                            ("4", "4GB"),
                            ("6", "6GB"),
                            ("8", "8GB"),
                            ("12", "12GB"),
                        ],
                        max_length=48,
                    ),
                ),
                ("model_storage", models.CharField(max_length=48)),
                (
                    "model_display",
                    models.CharField(
                        choices=[
                            ("LED", "LED"),
                            ("IPS", "IPS"),
                            ("AMO", "AMOLED"),
                            ("SAMO", "sAMOLED"),
                        ],
                        max_length=64,
                    ),
                ),
                ("model_price", models.IntegerField()),
                ("model_seller", models.CharField(max_length=128)),
                ("model_image", models.URLField(max_length=400)),
            ],
        ),
    ]
