# Generated by Django 4.1 on 2022-09-07 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mobile_store", "0003_mobilephone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mobilephone",
            name="model_seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
